"""add_user_subscription_fields

Revision ID: 0d6c8b56987d
Revises: 8bcbeb5c7674
Create Date: 2026-06-14 20:36:32.939818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0d6c8b56987d'
down_revision: Union[str, Sequence[str], None] = '8bcbeb5c7674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_type', sa.String(), server_default='NONE', nullable=False))
    op.add_column('users', sa.Column('subscription_duration_days', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_end_date')
    op.drop_column('users', 'subscription_duration_days')
    op.drop_column('users', 'subscription_type')
    # ### end Alembic commands ###
