"""Add current_version_index to ExecutionPlanItem

Revision ID: 8bcbeb5c7674
Revises: 8f12db9a446f
Create Date: 2026-06-13 20:11:53.689963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bcbeb5c7674'
down_revision: Union[str, Sequence[str], None] = '8f12db9a446f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_plan_items', sa.Column('current_version_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_plan_items', 'current_version_index')
    # ### end Alembic commands ###
