"""Add refinement_history to ExecutionPlanItem

Revision ID: 8f12db9a446f
Revises: a7ad424a488d
Create Date: 2026-06-13 20:09:00.363525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f12db9a446f'
down_revision: Union[str, Sequence[str], None] = 'a7ad424a488d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution_plan_items', sa.Column('refinement_history', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution_plan_items', 'refinement_history')
    # ### end Alembic commands ###
